# Generated by Selenium IDE

from selenium import webdriver
from Pages.homePage import HomePage


class Test_Home():
    def setup_method(self, method):
        self.driver = webdriver.Chrome("C:/Users/senan/Desktop/chromedriver.exe")
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_homepage(self):
        self.driver.get("https://www.kaft.com/")
        self.driver.set_window_size(1662, 902)
        home=HomePage(self.driver)
        home.homepage_menu()



