# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class HomePage():
    def __init__(self,driver):
        self.driver=driver

        self.menu="b"

    def teardown_method(self, method):
        self.driver.quit()

    def homepage_menu(self):
        self.driver.get("https://www.kaft.com/")
        self.driver.set_window_size(1662, 902)
        self.driver.find_element(By.LINK_TEXT, "Kapat").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR,self.menu)))
        self.driver.find_element(By.CSS_SELECTOR, self.menu).click()


