// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
namespace _net_test{
[TestFixture]
//driver.cs dosyasındaki Driver classı çağrılır
public class MyTest : Driver {
    //pom içindeki KaftTest classından test isimli bir obje tanımlanır.
    KaftTest test;
 
  
  [OneTimeSetUp]
  public void SetUp() {
      Initialize();
      test= new KaftTest(driver);
    
  }
  //Test işlemi pom içinde tanımlı fonksiyonların burada çağrılmasıyla gerçekleşir.
  [Test,Order(1)]
  public void kafttest() {
    test.getSite();
    test.menuClick();
    test.getCategory();
    test.productSelect();
    Assert.True(driver.Url.Contains("panoes_storm-pantolon/1524"));//kontrol işlemi yapılır
  }
  [OneTimeTearDown]
  protected void Close()
    {
        TearDown();
    }
}
}